### ISSUE TITLE
Race condition when archiving unlinked file (endless loop)

### ISSUE THREAD

**Issue by thiell** [phobos-storage/lustre-hsm-phobos#8]
Production was blocked today because a file being archived and opened by a copytool was unlinked.

The file had FID `0x280005c8f:0x6d76:0x0` and was being archived by this copytool:

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        4468 94.5  0.2 37634036 328104 ?     Ssl  10:12 353:06 /usr/bin/lhsmtool_phobos -q --default-family tape --fuid-xattr trusted.hsm_fuid /elm
```

The file was open in read-mode:
```
[root@elm-ent-dm03 ~]# ls -l /proc/4468/fd | grep 1272
lr-x------ 1 root root 64 Nov 14 10:36 1272 -> /elm/.lustre/fid/0x280005c8f:0x6d76:0x0
```

The file was deleted (we confirmed that thanks to changelogs that we log) after an HSM event (likely the archive event):

```
2025-11-14T10:36:54.495376725-0800 mdt=elm-MDT0002 id=3030558921 type=HSM   flags=0x680 uid=135432 gid=15432 target=[0x280005c8f:0x6d76:0x0]
2025-11-14T11:44:28.557422792-0800 mdt=elm-MDT0002 id=3031375587 type=UNLNK flags=0x0 uid=135432 gid=15432 target=[0x280005c8f:0x6d76:0x0] parent=[0x280005c5e:0x82f:0x0] name="2d26a391-2002-44ad-94a8-3e800bce16e7"
```

The copytool started to loop and log like crazy:
```
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559799000 <INFO> Too many reads of zero byte
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559805000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559811000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559816000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559822000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559828000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559833000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559839000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559845000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559850000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559856000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559862000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559865000 <INFO> Too many reads of zero byte
Nov 14 16:30:29 elm-ent-dm03 env[4468]: 2025-11-14 16:30:29.559870000 <VERBOSE> Read of zero byte from '/elm/.lustre/fid/0x280005c8f:0x6d76:0x0', 3902 are still missing
...
```

All other operations seemed also stuck on this data mover.

When I straced the copytool (PID 4468), I noticed this:

```
[root@elm-ent-dm03 ~]# strace -fp 4468
...
[pid  7813] gettid( <unfinished ...>
[pid  7813] <... gettid resumed>)       = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941098000 <V"..., 129) = 129
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941141000 <I"..., 65) = 65
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941210000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941275000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941343000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941408000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941473000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941536000 <V"..., 129) = 129
[pid  7813] read(1272, "", 3902)        = 0        <<<
[pid  7813] gettid()                    = 7813
[pid  7813] write(2, "2025-11-14 16:15:32.941603000 <V"..., 129) = 129
...
```

Again, 1272 was the file open in read mode:
```
[root@elm-ent-dm03 ~]# ls -l /proc/4468/fd | grep 1272
lr-x------ 1 root root 64 Nov 14 10:36 1272 -> /elm/.lustre/fid/0x280005c8f:0x6d76:0x0
```

read = 0 of a real file in lustre should abort the archival operation no?
There is a bug in the copytool IMO.

**Comment by CourrierGui** [comment]
The read loop is managed by Phobos not the copytool. So this is actually something that needs to be fixed in Phobos. The issue comes from the pho_posix_read function of Phobos. It returns 0 if nothing is actually read. But I don't think we check a 0 read and actually stop the I/O loop.

**Comment by CourrierGui** [comment]
This was actually already fixed in master. Phobos stops reading when it encounters an inconsistency between the file's expected size and the actual size read:

```
data processor reader expected 316 bytes to read and get only 158 bytes, at offset 158: Input/output error (5)
```

**Comment by thiell** [comment]
Hi @CourrierGui !

Thanks!

It looks like the issue is still present on master in pho_posix_read() here:

https://github.com/phobos-storage/phobos/blob/9b4e7cf79555a0f7052d61f5e22b80b7c3d75321/src/io-modules/io_posix_common.c#L789

But maybe this code is not used anymore in master, and instead `src/layout/posix_layout.c` is used (which I don't have in 2.2)?

**Comment by CourrierGui** [comment]
You are right, the function still doesn't consider a read returning 0 to be an error but the upper layers that do call this function (raid1 and raid4 layouts at the moment) check whether `ioa_read` (e.g. `pho_posix_read`) returned the expected number of bytes. The only exception is in the repack code (`copy_extent`) but we are less subject to this kind of race in that part of the code. So yes, `pho_posix_read` could still trigger an infinit loop but it is always called in a context where the returned value is checked against the expected one. I will add tests in Phobos to make sure that we fail if the size of the file is different from what's actually read by Phobos so that this behavior doesn't change in the futur. I will also probably check the number of bytes read in `copy_extent` so that we don't have this issue in the repack feature as well.

**Comment by CourrierGui** [comment]
While writing the tests I found a few bugs in the error path of the I/O code. So it seems that this is not supported by master either but for different reasons. I'll submit patches to fix these bugs.

**Comment by CourrierGui** [comment]
I've pushed the fix on this PR: https://github.com/phobos-storage/phobos/pull/59/files

**Comment by patlucas** [comment]
The PR is integrated on Phobos master.
